### Check data from pre-processing

In [49]:
import pandas as pd

In [51]:
df = pd.read_csv('doc2vec.csv', names = ['dummy'] + list(range(300)), header = None)
df = df.iloc[1:, :]
df = df.drop(['dummy'], axis = 1)
print(df.shape)
df.head()

(49135, 300)


0         1         2         3         4         5         6    \
1  0.430593 -0.466050 -0.470676  1.054820  0.316000 -0.130199  0.315110   
2  0.637994 -0.193419 -0.244674  0.679882 -0.071950 -0.014554  0.034619   
3  0.147555 -0.658567 -0.573996  0.415267 -0.620533  0.019823  0.085184   
4  0.402968  0.085815 -0.414460 -0.190086 -0.466714  0.001200 -0.095993   
5  0.529395 -0.123117 -0.597903  0.238643 -0.158196  0.055387  0.050731   

        7         8         9      ...          290       291       292  \
1 -0.335515 -0.161534 -0.256116    ...    -0.164257  0.655501  0.455939   
2 -0.226025 -0.273253 -0.312995    ...    -0.361931  0.342828  0.294746   
3 -0.410821 -0.105631 -0.703927    ...    -0.104995  0.483964  0.045553   
4 -0.784641 -0.789203 -0.510079    ...    -0.120400  0.129661  0.052883   
5 -0.341268 -0.027313 -0.198758    ...    -0.085786  0.251621  0.482779   

        293       294       295       296       297       298       299  
1 -0.885223  0.311449  0.484732  0.685058 -0.197346  0.160982 -0.207872  
2 -0.610690  0.082077  0.107635  0.301264  0.067374  0.173405 -0.391880  
3 -0.224484  0.153301  0.451102  0.386119  0.096559 -0.381728 -0.364295  
4 -0.122680  0.159227  0.391799  0.350398  0.101186 -0.590261 -0.277878  
5 -0.660892  0.026911  0.226880  0.281872  0.048325  0.055828 -0.288095  

[5 rows x 300 columns]

In [35]:
import numpy as np

total_words = []
for i in range(10):
    
    doc = []

    word1 = [1, 2, 3]
    word2 = [4, 5, 6]
    word3 = [7, 8, 9]

    doc.append(word1)
    doc.append(word2)
    doc.append(word3)
    
    doc = np.mean(doc, axis = 0)

    
    total_words.append(doc)

In [26]:
print('Shape: ', np.shape(total_words))
for doc in total_words:
    print(doc)

Shape:  (10, 3)
[4. 5. 6.]
[4. 5. 6.]
[4. 5. 6.]
[4. 5. 6.]
[4. 5. 6.]
[4. 5. 6.]
[4. 5. 6.]
[4. 5. 6.]
[4. 5. 6.]
[4. 5. 6.]
